import { faker } from '@faker-js/faker';
import {
  Category,
  ExperienceLevel,
  JOB_LISTING_STATUS,
  JobType,
} from '../interfaces';

const job_listings = [
  {
    title: 'Software Developer',
    companyName: 'Tech Solutions Inc.',
    companyDetails: 'Leading tech company',
    jobResponsibilities: ['Develop and maintain software applications.'],
    jobRequirements: "Bachelor's degree in Computer Science.",
    salary: 'Competitive',
    experienceLevel: ExperienceLevel.SENIOR,
    jobType: JobType.FULLTIME,
    industry: 'Technology',
    location: 'San Francisco, CA',
    languages: 'Java, JavaScript',
    skills: ['Software Development'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Marketing Specialist',
    companyName: 'Marketing Pro',
    companyDetails: 'Marketing agency',
    jobResponsibilities: ['Plan and execute marketing campaigns.'],
    jobRequirements: "Bachelor's degree in Marketing.",
    salary: '$45,000 - $55,000',
    experienceLevel: ExperienceLevel.SENIOR,
    jobType: JobType.FULLTIME,
    industry: 'Marketing',
    location: 'New York, NY',
    languages: 'English, Spanish',
    skills: ['Digital Marketing', 'Social Media'],
    category: Category.ONSITE,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Data Analyst',
    companyName: 'Data Insights Ltd.',
    companyDetails: 'Data analysis firm',
    jobResponsibilities: ['Analyze and interpret data for insights.'],
    jobRequirements: "Bachelor's degree in Statistics or related field.",
    salary: '$50,000 - $60,000',
    experienceLevel: ExperienceLevel.SENIOR,
    jobType: JobType.FULLTIME,
    industry: 'Data',
    location: 'Chicago, IL',
    languages: ['SQL', 'Python'],
    skills: ['Data Analysis', 'Statistics'],
    category: Category.ONSITE,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Graphic Designer',
    companyName: 'Creative Designs Co.',
    companyDetails: 'Graphic design agency',
    jobResponsibilities: ['Create visually appealing designs for clients.'],
    jobRequirements: "Bachelor's degree in Graphic Design.",
    salary: '$40,000 - $50,000',
    experienceLevel: ExperienceLevel.SENIOR,
    jobType: JobType.FULLTIME,
    industry: 'Design',
    location: 'Los Angeles, CA',
    languages: ['Photoshop', 'Illustrator'],
    skills: ['Graphic Design', 'Adobe Creative Suite'],
    category: Category.ONSITE,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Sales Representative',
    companyName: 'Sales Pro Inc.',
    companyDetails: 'Sales and marketing company',
    jobResponsibilities: ['Sell products and services to clients.'],
    jobRequirements: 'High school diploma or equivalent.',
    salary: '$35,000 - $45,000',
    experienceLevel: ExperienceLevel.JUNIOR,
    jobType: JobType.FULLTIME,
    industry: 'Sales',
    location: 'Houston, TX',
    languages: ['English', 'Spanish'],
    skills: ['Sales', 'Customer Relations'],
    category: Category.ONSITE,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Web Developer',
    companyName: 'WebTech Solutions',
    companyDetails: 'Web development agency',
    jobResponsibilities: ['Design and develop websites for clients.'],
    jobRequirements: "Bachelor's degree in Computer Science.",
    salary: '$50,000 - $60,000',
    experienceLevel: ExperienceLevel.JUNIOR,
    jobType: JobType.FULLTIME,
    industry: 'Technology',
    location: 'Seattle, WA',
    languages: ['HTML', 'CSS', 'JavaScript'],
    skills: ['Web Development'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.APPROVED,
  },
  {
    title: 'Content Writer',
    companyName: 'Content Creations Co.',
    companyDetails: 'Content creation agency',
    jobResponsibilities: ['Write engaging content for various platforms.'],
    jobRequirements: "Bachelor's degree in English or related field.",
    salary: '$40,000 - $50,000',
    experienceLevel: ExperienceLevel.INTERNSHIP,
    jobType: JobType.FULLTIME,
    industry: 'Content',
    location: 'Boston, MA',
    languages: ['English'],
    skills: ['Content Writing', 'SEO'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Financial Analyst',
    companyName: 'Finance Experts Inc.',
    companyDetails: 'Financial advisory firm',
    jobResponsibilities: [
      'Analyze financial data and provide recommendations.',
    ],
    jobRequirements: "Bachelor's degree in Finance or related field.",
    salary: '$55,000 - $65,000',
    experienceLevel: ExperienceLevel.INTERNSHIP,
    jobType: JobType.FULLTIME,
    industry: 'Finance',
    location: 'Miami, FL',
    languages: ['Excel', 'SQL'],
    skills: ['Financial Analysis', 'Excel'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Human Resources Coordinator',
    companyName: 'HR Solutions Ltd.',
    companyDetails: 'Human resources consulting firm',
    jobResponsibilities: ['Manage HR processes and assist with recruitment.'],
    jobRequirements: "Bachelor's degree in Human Resources or related field.",
    salary: '$45,000 - $55,000',
    experienceLevel: ExperienceLevel.INTERNSHIP,
    jobType: JobType.FULLTIME,
    industry: 'Human Resources',
    location: 'Dallas, TX',
    languages: ['English', 'Spanish'],
    skills: ['HR Management', 'Recruitment'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Customer Support Specialist',
    companyName: 'Support Solutions Inc.',
    companyDetails: 'Customer support services',
    jobResponsibilities: ['Provide assistance and resolve customer issues.'],
    jobRequirements: 'High school diploma or equivalent.',
    salary: '$30,000 - $40,000',
    experienceLevel: ExperienceLevel.INTERNSHIP,
    jobType: JobType.FULLTIME,
    industry: 'Customer Support',
    location: 'Phoenix, AZ',
    languages: ['English', 'Spanish'],
    skills: ['Customer Service', 'Problem Solving'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.REJECTED,
  },
  {
    title: 'Software Engineer',
    companyName: 'CodeCrafters LLC',
    companyDetails: 'Software development company',
    jobResponsibilities: ['Develop and maintain software applications.'],
    jobRequirements: "Bachelor's degree in Computer Science.",
    salary: '$55,000 - $65,000',
    experienceLevel: ExperienceLevel.INTERNSHIP,
    jobType: JobType.TEMPORARY,
    industry: 'Technology',
    location: 'Austin, TX',
    languages: ['Java', 'Python'],
    skills: ['Software Development'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.REJECTED,
  },
  {
    title: 'Marketing Coordinator',
    companyName: 'Marketing Innovations Inc.',
    companyDetails: 'Marketing agency',
    jobResponsibilities: ['Assist in the execution of marketing campaigns.'],
    jobRequirements: "Bachelor's degree in Marketing or related field.",
    salary: '$40,000 - $50,000',
    experienceLevel: ExperienceLevel.JUNIOR,
    jobType: JobType.TEMPORARY,
    industry: 'Marketing',
    location: 'Denver, CO',
    languages: ['English', 'French'],
    skills: ['Marketing', 'Campaign Management'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.REJECTED,
  },
  {
    title: 'Data Scientist',
    companyName: 'Data Insights Ltd.',
    companyDetails: 'Data analysis firm',
    jobResponsibilities: [
      'Apply data science techniques to solve business problems.',
    ],
    jobRequirements: "Master's degree in Data Science or related field.",
    salary: '$60,000 - $70,000',
    experienceLevel: ExperienceLevel.MIDLEVEL,
    jobType: JobType.FULLTIME,
    industry: 'Data',
    location: 'San Diego, CA',
    languages: ['Python', 'R'],
    skills: ['Data Science', 'Machine Learning'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.REJECTED,
  },
  {
    title: 'UI/UX Designer',
    companyName: 'DesignWorks Inc.',
    companyDetails: 'User interface and user experience design agency',
    jobResponsibilities: [
      'Create intuitive and visually appealing user interfaces.',
    ],
    jobRequirements: "Bachelor's degree in Design or related field.",
    salary: '$45,000 - $55,000',
    experienceLevel: ExperienceLevel.MIDLEVEL,
    jobType: JobType.FULLTIME,
    industry: 'Design',
    location: 'Portland, OR',
    languages: ['Sketch', 'Figma'],
    skills: ['UI/UX Design', 'Prototyping'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Accountant',
    companyName: 'Financial Experts Ltd.',
    companyDetails: 'Accounting and financial services firm',
    jobResponsibilities: ['Manage financial records and perform audits.'],
    jobRequirements: "Bachelor's degree in Accounting or related field.",
    salary: '$50,000 - $60,000',
    experienceLevel: ExperienceLevel.MIDLEVEL,
    jobType: JobType.CONTRACT,
    industry: 'Finance',
    location: 'Philadelphia, PA',
    languages: ['Excel'],
    skills: ['Financial Accounting', 'Auditing'],
    category: Category.REMOTE,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'HR Assistant',
    companyName: 'HR Solutions Ltd.',
    companyDetails: 'Human resources consulting firm',
    jobResponsibilities: [
      'Provide administrative support to the HR department.',
    ],
    jobRequirements: 'High school diploma or equivalent.',
    salary: '$35,000 - $45,000',
    experienceLevel: ExperienceLevel.MIDLEVEL,
    jobType: JobType.CONTRACT,
    industry: 'Human Resources',
    location: 'Las Vegas, NV',
    languages: ['English', 'Spanish'],
    skills: ['HR Administration', 'Office Support'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Customer Service Representative',
    companyName: 'Customer Care Inc.',
    companyDetails: 'Customer service solutions provider',
    jobResponsibilities: ['Assist customers with inquiries and issues.'],
    jobRequirements: 'High school diploma or equivalent.',
    salary: '$30,000 - $40,000',
    experienceLevel: ExperienceLevel.JUNIOR,
    jobType: JobType.CONTRACT,
    industry: 'Customer Support',
    location: 'Atlanta, GA',
    languages: ['English', 'Spanish'],
    skills: ['Customer Support', 'Communication'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Frontend Developer',
    companyName: 'WebTech Solutions',
    companyDetails: 'Web development agency',
    jobResponsibilities: ['Design and develop user interfaces for websites.'],
    jobRequirements: "Bachelor's degree in Computer Science.",
    salary: '$50,000 - $60,000',
    experienceLevel: ExperienceLevel.JUNIOR,
    jobType: JobType.CONTRACT,
    industry: 'Technology',
    location: 'Raleigh, NC',
    languages: ['HTML', 'CSS', 'JavaScript'],
    skills: ['Web Development', 'UI Design'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.PENDING,
  },
  {
    title: 'Content Editor',
    companyName: 'Content Creations Co.',
    companyDetails: 'Content creation agency',
    jobResponsibilities: [
      'Edit and proofread content for accuracy and quality.',
    ],
    jobRequirements: `Bachelor's degree in English or related field.`,
    salary: '$40,000 - $50,000',
    experienceLevel: ExperienceLevel.SENIOR,
    jobType: JobType.FULLTIME,
    industry: 'Content',
    location: 'Nashville, TN',
    languages: ['English'],
    skills: ['Editing', 'Proofreading'],
    category: Category.HYBRID,
    status: JOB_LISTING_STATUS.PENDING,
  },
];
faker.seed(11224);

export const job_listingSeed = job_listings.map((jobs) => ({
  id: faker.string.uuid(),
  ...jobs,
}));
